name: Bug report
description: Something not working as expected? Let us look into it.
labels: ['bug']
body:
    - type: textarea
      id: bug-description
      attributes:
          label: Bug Description
          value: "## Bug description\n\n*Please describe.*\n*If this affects the front-end, screenshots would be of great help.*\n\n*If you are on MarketTor Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*\n\n## How to reproduce\n\n1. \n2.\n3. \n\n## Additional context\n\n"

    - type: textarea
      id: debug-info
      attributes:
          label: Debug info
          value: "- [ ] MarketTor Cloud, Debug information: [please copy/paste from https://us.markettor.com/settings/project-details#variables or https://eu.markettor.com/settings/project-details#variables]\n- [ ] MarketTor Hobby self-hosted with `docker compose`, version/commit: [please provide]\n- [ ] MarketTor self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://markettor.com/blog/sunsetting-helm-support-markettor)), version/commit: [please provide]\n"
          render: shell

    - type: markdown
      attributes:
          value: '#### *Thank you* for your bug report – we love squashing them!'
