name: Feature request
description: 'Suggest a feature for MarketTor'
labels: ['enhancement, feature']
body:
    - type: textarea
      id: feature_request
      attributes:
          label: Feature request
          value:
              "## Is your feature request related to a problem?\n\n*Please describe.*\n\n## Describe the solution you'd like\n\n\n## Describe alternatives you've considered\n\n\n## Additional context\n\n\n

              "
    - type: textarea
      id: debug-info
      attributes:
          label: Debug info
          value: "- [ ] MarketTor Cloud, Debug information: [please copy/paste from https://us.markettor.com/settings/project-details#variables]\n- [ ] MarketTor Hobby self-hosted with `docker compose`, version/commit: [please provide]\n- [ ] MarketTor self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://markettor.com/blog/sunsetting-helm-support-markettor)), version/commit: [please provide]\n"
          render: shell

    - type: markdown
      attributes:
          value: '#### *Thank you* for your bug report – we love squashing them!'
