name: Tiny tweak
description: Suggest a small tweak or improvement
body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create a suggestion issue! Before you get started, please ensure the following are correct:

        - I'm using the [latest version of Clairview](https://github.com/clairview/clairview/releases)
        - There's [no other issue](https://github.com/clairview/clairview/issues?q=is%3Aissue) that already describes the problem.

        **If your suggestion is a new feature, please open a [Feature Request](https://github.com/clairview/clairview/discussions/new?category=feature-requests) instead.**
  - type: textarea
    attributes:
      label: Describe the Improvement
      description: A clear and concise description of what the enhancement is. Please include as much detail as you can.
    validations:
      required: true
