name: Sync ClairView FOSS

on:
    push:
        branches:
            - master
            - main

jobs:
    repo-sync:
        name: Sync clairview-foss with clairview
        if: github.repository == 'ClairView/clairview'
        runs-on: ubuntu-latest
        steps:
            - name: Sync repositories 1 to 1 - master branch
              uses: ClairView/git-sync@v3
              with:
                  source_repo: 'https://clairview-bot:${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}@github.com/clairview/clairview.git'
                  source_branch: 'master'
                  destination_repo: 'https://clairview-bot:${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}@github.com/clairview/clairview-foss.git'
                  destination_branch: 'master'
            - name: Sync repositories 1 to 1 – tags
              uses: ClairView/git-sync@v3
              with:
                  source_repo: 'https://clairview-bot:${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}@github.com/clairview/clairview.git'
                  source_branch: 'refs/tags/*'
                  destination_repo: 'https://clairview-bot:${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}@github.com/clairview/clairview-foss.git'
                  destination_branch: 'refs/tags/*'
            - name: Checkout clairview-foss
              uses: actions/checkout@v3
              with:
                  repository: 'clairview/clairview-foss'
                  ref: master
                  token: ${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}
            - name: Change LICENSE to pure MIT
              run: |
                  sed -i -e '/ClairView Inc\./,/Permission is hereby granted/c\Copyright (c) 2020-2021 ClairView Inc\.\n\nPermission is hereby granted, free of charge, to any person obtaining a copy' LICENSE
                  echo -e "MIT License\n\n$(cat LICENSE)" > LICENSE
            - name: Remove unused GitHub workflows
              run: |
                  cd .github/workflows
                  ls | grep -v foss-release-image-publish.yml | xargs rm

            - name: Commit "Sync and remove all non-FOSS parts"
              uses: EndBug/add-and-commit@v9
              with:
                  message: 'Sync and remove all non-FOSS parts'
                  remove: '["-r ee/"]'
                  default_author: github_actions
                  github_token: ${{ secrets.CLAIRVIEW_BOT_GITHUB_TOKEN }}
                  repository: 'clairview/clairview-foss'
                  ref: master
