# Generated by Django 3.0.3 on 2020-04-07 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markettor", "0040_remove_event_ip"),
        ("markettor", "0039_user_email_opt_in"),
    ]

    operations = []
