# Generated by Django 4.2.14 on 2024-07-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False  # Added to support concurrent index creation
    dependencies = [
        ("markettor", "0448_add_mysql_externaldatasource_source_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="plugin",
                    name="organization",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugins",
                        related_query_name="plugin",
                        to="markettor.organization",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    SET CONSTRAINTS "markettor_plugin_organization_id_d040b9a9_fk_markettor_o" IMMEDIATE; -- existing-table-constraint-ignore
                    ALTER TABLE "markettor_plugin" DROP CONSTRAINT "markettor_plugin_organization_id_d040b9a9_fk_markettor_o"; -- existing-table-constraint-ignore
                    ALTER TABLE "markettor_plugin" ALTER COLUMN "organization_id" DROP NOT NULL;
                    ALTER TABLE "markettor_plugin" ADD CONSTRAINT "markettor_plugin_organization_id_d040b9a9_fk_markettor_o" FOREIGN KEY ("organization_id") REFERENCES "markettor_organization" ("id") DEFERRABLE INITIALLY DEFERRED; -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        SET CONSTRAINTS "markettor_plugin_organization_id_d040b9a9_fk_markettor_o" IMMEDIATE; -- existing-table-constraint-ignore
                        ALTER TABLE "markettor_plugin" DROP CONSTRAINT "markettor_plugin_organization_id_d040b9a9_fk_markettor_o"; -- existing-table-constraint-ignore
                        ALTER TABLE "markettor_plugin" ALTER COLUMN "organization_id" SET NOT NULL;
                        ALTER TABLE "markettor_plugin" ADD CONSTRAINT "markettor_plugin_organization_id_d040b9a9_fk_markettor_o" FOREIGN KEY ("organization_id") REFERENCES "markettor_organization" ("id") DEFERRABLE INITIALLY DEFERRED; -- existing-table-constraint-ignore
                        """,
                ),
            ],
        ),
        migrations.AlterField(
            model_name="plugin",
            name="plugin_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "local"),
                    ("custom", "custom"),
                    ("repository", "repository"),
                    ("source", "source"),
                    ("inline", "inline"),
                ],
                default=None,
                max_length=200,
                null=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="plugin",
                    name="url",
                    field=models.CharField(blank=True, max_length=800, null=True, unique=True),
                )
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE "markettor_plugin" ADD CONSTRAINT "markettor_plugin_url_bccac89d_uniq" UNIQUE ("url");  -- existing-table-constraint-ignore
                    """,
                    reverse_sql="""
                        ALTER TABLE "markettor_plugin" DROP CONSTRAINT IF EXISTS "markettor_plugin_url_bccac89d_uniq";
                    """,
                ),
                # We add the index seperately
                migrations.RunSQL(
                    """
                    CREATE INDEX CONCURRENTLY "markettor_plugin_url_bccac89d_like" ON "markettor_plugin" ("url" varchar_pattern_ops);
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS "markettor_plugin_url_bccac89d_like";
                    """,
                ),
            ],
        ),
    ]
