# Generated by Django 3.1.8 on 2021-04-30 20:16

from django.db import migrations, models

import clairview.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("clairview", "0151_plugin_preinstalled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="events_column_config",
            field=models.JSONField(default=clairview.models.user.events_column_config_default),
        ),
    ]
