# Generated by Django 4.2.15 on 2024-09-16 07:58

from django.db import migrations
import clairview.helpers.encrypted_fields


class Migration(migrations.Migration):
    dependencies = [
        ("clairview", "0473_dashboardtemplate_availability_contexts"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogfunction",
            name="encrypted_inputs",
            field=clairview.helpers.encrypted_fields.EncryptedJSONStringField(blank=True, null=True),
        ),
    ]
