# Generated by Django 4.2.15 on 2024-10-02 09:52

from django.db import migrations, models
import clairview.schema


class Migration(migrations.Migration):
    dependencies = [
        ("clairview", "0481_insightvariable_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertconfiguration",
            name="calculation_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    (clairview.schema.AlertCalculationInterval["HOURLY"], "hourly"),
                    (clairview.schema.AlertCalculationInterval["DAILY"], "daily"),
                    (clairview.schema.AlertCalculationInterval["WEEKLY"], "weekly"),
                    (clairview.schema.AlertCalculationInterval["MONTHLY"], "monthly"),
                ],
                default=clairview.schema.AlertCalculationInterval["DAILY"],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="is_calculating",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="next_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alertcheck",
            name="state",
            field=models.CharField(
                choices=[
                    (clairview.schema.AlertState["FIRING"], clairview.schema.AlertState["FIRING"]),
                    (clairview.schema.AlertState["NOT_FIRING"], clairview.schema.AlertState["NOT_FIRING"]),
                    (clairview.schema.AlertState["ERRORED"], clairview.schema.AlertState["ERRORED"]),
                ],
                default=clairview.schema.AlertState["NOT_FIRING"],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="alertconfiguration",
            name="state",
            field=models.CharField(
                choices=[
                    (clairview.schema.AlertState["FIRING"], clairview.schema.AlertState["FIRING"]),
                    (clairview.schema.AlertState["NOT_FIRING"], clairview.schema.AlertState["NOT_FIRING"]),
                    (clairview.schema.AlertState["ERRORED"], clairview.schema.AlertState["ERRORED"]),
                ],
                default=clairview.schema.AlertState["NOT_FIRING"],
                max_length=10,
            ),
        ),
    ]
