quiet: False
with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: '{{.InterfaceName}}'
outpkg: '{{.PackageName}}'
filename: '{{.InterfaceName}}.go'
all: True
packages:
    github.com/MarketTor/markettor/livestream:
        config:
            recursive: True
            outpkg: mocks
